# Generated by Django 5.0.3 on 2024-04-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='duracao',
            field=models.IntegerField(verbose_name='Duração do curso em meses'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='numero_faltas',
            field=models.IntegerField(verbose_name='Número de faltas'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='telefone',
            field=models.IntegerField(verbose_name='Telefone da instituição'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='periodo',
            field=models.IntegerField(verbose_name='Período do curso'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='cpf',
            field=models.IntegerField(verbose_name='CPF da pessoa'),
        ),
    ]
