# Generated by Django 5.0.3 on 2024-04-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_instituicao_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Nome da disciplina'),
        ),
    ]
