# Generated by Django 5.0.3 on 2024-04-01 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cursos_duracao_alter_frequencia_numero_faltas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipodeAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do tipo de avaliação')),
            ],
            options={
                'verbose_name': 'Tipo de Avaliação',
                'verbose_name_plural': 'Tipos de Avaliação',
            },
        ),
        migrations.CreateModel(
            name='DisciplinasporCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.CharField(max_length=100, verbose_name='Carga Horária')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplina')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periodo', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Carga Horária',
                'verbose_name_plural': 'Cargas Horárias',
            },
        ),
    ]
