# Generated by Django 5.0.3 on 2024-04-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_disciplinasporcursos_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplinasporcursos',
            old_name='disciplina',
            new_name='disciplinasporcursos',
        ),
    ]
