# Generated by Django 5.0.3 on 2024-04-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_disciplina_disciplinasporcursos_disciplinasporcursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinasporcursos',
            name='periodo',
            field=models.CharField(max_length=100, verbose_name='Disciplina por curso'),
        ),
    ]
