# Generated by Django 5.0.3 on 2024-04-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_disciplina_por_curso_disciplina'),
        ('app', '0009_alter_disciplinasporcursos_disciplinasporcursos_and_more'),
    ]

    operations = [
    ]
